---
version: "2.1"
services:
  sonarr:
    #image: ghcr.io/linuxserver/sonarr:3.0.9.1549-ls160
    image: ghcr.io/linuxserver/sonarr:3.0.10.1566-ls182
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./config:/config
      - ./tvshows:/tv
      - ./anime:/anime
      - ./movies:/movies
      - ../qbittorrent/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - web
      - default
    labels:
        - "traefik.enable=true"
        # HTTPS Rules
        - "traefik.http.routers.sonarr_SSL.rule=Host(`sonarr.atomicc.be`)"
        - "traefik.http.routers.sonarr_SSL.entrypoints=https"
        - "traefik.http.routers.sonarr_SSL.tls.certresolver=letsencrypt"
        - "traefik.http.routers.sonarr_SSL.tls=true"
        - "traefik.http.services.sonarr_SSL.loadbalancer.server.port=8989"
        # HTTP
        - "traefik.http.routers.sonarr.rule=Host(`sonarr.atomicc.be`)"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.sonarr.entrypoints=http"
        - "traefik.http.routers.sonarr.middlewares=https-redirect"
networks:
 web:
   external: true
 default:
   external:
     name: sonarr_bittorrent
