version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - TZ=Europe/Brussels

      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=192.168.0.107
      - serverPort=8266
      - webUIPort=8265
      - internalNode=false
      - nodeID=MyInternalNode
    volumes:
      - ./persist/tdarr/server:/app/server
      - ./persist/tdarr/configs:/app/configs
      - ./persist/tdarr/logs:/app/logs
      - ../../docker:/media
      - ./persist/transcode_cache:/temp


# node example
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - TZ=Europe/Brussels
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - nodeID=MainNode
      - serverIP=192.168.0.107
      - serverPort=8266
    volumes:
      - ./persist/tdarr/configs:/app/configs
      - ./persist/tdarr/logs:/app/logs
      - ../../docker:/media
      - ./persist/transcode_cache:/temp
