version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./config:/config
    ports:
      - 8091:80
    restart: unless-stopped
    networks:
     - web
    labels:
        - "traefik.enable=true"
        # HTTPS Rules
        - "traefik.http.routers.heimdall_SSL.rule=Host(`heimdall.atomicc.be`)"
        - "traefik.http.routers.heimdall_SSL.entrypoints=https"
        - "traefik.http.routers.heimdall_SSL.tls.certresolver=letsencrypt"
        - "traefik.http.routers.heimdall_SSL.tls=true"
        - "traefik.http.services.heimdall_SSL.loadbalancer.server.port=80"
        # HTTP
        - "traefik.http.routers.heimdall.rule=Host(`heimdall.atomicc.be`)"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.heimdall.entrypoints=http"
        - "traefik.http.routers.heimdall.middlewares=https-redirect"
networks:
 web:
   external: true
