version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - AUTO_UPDATE=true #optional
      #- RUN_OPTS=<run options here> #optional
    volumes:
      - /home/atomic/Docker/jackett/config:/config
      - /home/atomic/Docker/jackett/Torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
