version: '3.3'

volumes:
  uptimekuma:

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.18.5
      #image: louislam/uptime-kuma:1.17.1
    container_name: uptime-kuma
    volumes:
      - uptimekuma:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped 
    networks:
        - web
        - default
    labels:
        - "traefik.enable=true"
        # HTTPS Rules
        - "traefik.http.routers.kuma_SSL.rule=Host(`kuma.atomicc.be`)"
        - "traefik.http.routers.kuma_SSL.entrypoints=https"
        - "traefik.http.routers.kuma_SSL.tls.certresolver=letsencrypt"
        - "traefik.http.routers.kuma_SSL.tls=true"
        - "traefik.http.services.kuma_SSL.loadbalancer.server.port=3001"
        # HTTP
        - "traefik.http.routers.kuma.rule=Host(`kuma.atomicc.be`)"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.kuma.entrypoints=http"
        - "traefik.http.routers.kuma.middlewares=https-redirect"
networks:
 web:
   external: true
